# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [1]:
import numpy as np

In [3]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
arr = np.random.randint(1,20,25).reshape(5,5)
arr

array([[ 7,  2, 17,  5,  7],
       [ 2,  8,  7,  7,  7],
       [18,  8,  1, 17,  4],
       [ 4,  4,  7, 10,  9],
       [ 8,  9, 18, 14,  4]], dtype=int32)

In [14]:
arr[:,2] = 1
arr

array([[ 7,  2,  1,  5,  7],
       [ 2,  8,  1,  7,  7],
       [18,  8,  1, 17,  4],
       [ 4,  4,  1, 10,  9],
       [ 8,  9,  1, 14,  4]], dtype=int32)

In [18]:
arr2 = np.arange(1,17).reshape(4,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [24]:
for i in range(arr2.shape[0]):
    arr2[i,i] = 0

In [25]:
arr2

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [28]:
arr4 = np.arange(1,37).reshape(6,6)
arr4

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [31]:
arr4[2:5,]

array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [32]:
arr4[2:5,1:4]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [47]:
arr5 = np.random.randint(1, 21, size=(5, 5))
arr5

array([[ 2,  8, 16,  2, 19],
       [ 2, 10, 19,  1,  8],
       [19,  2,  6, 13,  9],
       [ 1,  8, 17, 14,  2],
       [10,  2,  7,  1, 17]], dtype=int32)

In [52]:
arr5[0,],arr5[:,0], arr5[4,:], arr5[:,4]

(array([ 2,  8, 16,  2, 19], dtype=int32),
 array([ 2,  2, 19,  1, 10], dtype=int32),
 array([10,  2,  7,  1, 17], dtype=int32),
 array([19,  8,  9,  2, 17], dtype=int32))

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [57]:
arr_a = np.random.random( size= (3,4)) *100
arr_b = np.random.random( size= (3,4)) *100

In [58]:
arr_a + arr_b

array([[ 90.62775522,  51.43055413,  88.24619162,  99.3776353 ],
       [182.11741695,  72.4636769 ,  66.77454597, 165.09445322],
       [ 85.8826402 , 120.14867911, 111.30682602,  28.79727753]])

In [59]:
arr_a - arr_b

array([[-77.25916322,  -9.06488368, -88.19494793, -94.66485143],
       [ -7.36845656,   1.25641552,  -8.91702563, -23.06404698],
       [-30.37226908,  49.7126755 ,   2.49331913,  24.95111525]])

In [60]:
arr_a * arr_b

array([[5.61102929e+02, 6.40732445e+02, 2.26037353e+00, 2.28620075e+02],
       [8.27811485e+03, 1.31235147e+03, 1.09483166e+03, 6.68105706e+03],
       [1.61333829e+03, 2.99108875e+03, 3.09574822e+03, 5.16812603e+01]])

In [61]:
arr_a / arr_b

array([[7.96285507e-02, 7.00311825e-01, 2.90429346e-04, 2.42873813e-02],
       [9.22226851e-01, 1.03528897e+00, 7.64385243e-01, 7.54844485e-01],
       [4.77488404e-01, 2.41157002e+00, 1.04582738e+00, 1.39745515e+01]])

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [64]:
arr6 = np.arange(1,17).reshape(4,4)
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr6.sum(axis=0) # column wise sum

array([28, 32, 36, 40])

In [67]:
arr6.sum(axis=1)

array([10, 26, 42, 58])

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [72]:
arr6 = np.random.random(size= (5,5)) *100
arr6

array([[18.21289932, 94.3187034 , 26.83762798, 24.09984382, 75.55019172],
       [59.65119929, 87.56718071,  7.75745615, 83.7657208 , 22.74569911],
       [24.80560111, 55.56721374, 36.59823279, 33.91642422, 75.64140515],
       [28.39530364, 40.82853525, 68.26765906, 74.69993944,  1.89212008],
       [98.74312018, 74.65751382, 80.50732028, 57.48296263, 87.97571935]])

In [77]:
# arr6.mean(),arr6.med()
np.mean(arr6),np.median(arr6), np.std(arr6), np.var(arr6),  np.std(arr6) **2

(np.float64(53.61942372171366),
 np.float64(57.482962626206216),
 np.float64(28.74875578043526),
 np.float64(826.4909589231098),
 np.float64(826.4909589231098))

2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [79]:
arr7  = np.arange(1,10).reshape(3,3)
arr7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
np.mean(arr7), np.std(arr7)

(np.float64(5.0), np.float64(2.581988897471611))

In [86]:
# np.mean((arr7 - np.mean(arr7))/np.std(arr7)),np.std((arr7 - np.mean(arr7))/np.std(arr7))
(arr7 - np.mean(arr7))/np.std(arr7)

array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [91]:
arr8 = np.arange(1,10,).reshape( (3,3))
arr8
arr8 + np.random.randint(1, 11, size=(3,))

array([[10,  3,  6],
       [13,  6,  9],
       [16,  9, 12]])

2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [94]:
arr9 = np.arange(1,17,).reshape( (4,4))
arr9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [95]:
arr9 + np.random.randint(1, 17, size=(4,))

array([[ 7,  3, 15, 16],
       [11,  7, 19, 20],
       [15, 11, 23, 24],
       [19, 15, 27, 28]])

### Assignment 6: Linear Algebra

2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [96]:
# Create two NumPy arrays of shape (2, 3) and (3, 2)
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform matrix multiplication
result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

Array 1:
[[9 9 7]
 [6 1 8]]
Array 2:
[[ 6  4]
 [ 6 10]
 [ 5  6]]
Matrix multiplication result:
[[143 168]
 [ 82  82]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [98]:
np.arange(1,10).reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [105]:
arr10 = np.arange(1,26).reshape(25,1)
arr10.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [107]:
arr11 = np.arange(1,26).reshape(5,5)
arr11

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [112]:
arr11[[0,0,4,4],[0,4,0,4]]

array([ 1,  5, 21, 25])

2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [116]:
arr12 = np.random.randint(1,16,16).reshape(4,4)
arr12

array([[11,  1,  3,  9],
       [11, 12,  4,  5],
       [14, 12,  8,  4],
       [11,  1,  3,  8]], dtype=int32)

In [118]:
arr12[arr12 > 10] = 10
arr12

array([[10,  1,  3,  9],
       [10, 10,  4,  5],
       [10, 10,  8,  4],
       [10,  1,  3,  8]], dtype=int32)

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [119]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)

print(data)

[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]


In [ ]:
sorted_data = np.sort(data, order='age',)
print("Sorted array by age:")
print(sorted_data)

Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [122]:
np.newaxis

In [121]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [126]:
import numpy.ma as ma

In [127]:
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[11 16 12  8]
 [ 2  8  1 18]
 [ 7 17  5 16]
 [ 6 20 11  9]]
Masked array:
[[-- -- -- 8]
 [2 8 1 --]
 [7 -- 5 --]
 [6 -- -- 9]]
Sum of unmasked elements: 46
